### ISSUE TITLE
Attribute for skipping a field?

### ISSUE THREAD

**Issue by Longor1996** [martin-t/cvars#3]
I've got some structs with fields that must not be changed (would cause crashing and/or freezing), but would like to keep the remaining fields configurable...

Would it be possible to add something like a `#[cvars(skip)]` attribute, similar to `#[serde(skip)]`? Maybe check for the latter too?

**Comment by martin-t** [comment]
Yeah, `#[cvars(skip)]` shouldn't be too hard. Probably a bad idea to check for a different crate's attributes though - too surprising behavior.

**Comment by martin-t** [comment]
I pushed it in 134a8c7a3519d19822f3e55a73c6a122da319f32 - should be usable if you depend on this commit directly. I'll do some cleanup, better diagnostics and release a new version tomorrow.

**Comment by Longor1996** [comment]
Got a (very obvious in hindsight) idea: A `#[cvars(readonly)]`-attribute, for fields that can only be inspected. Could be used for both scripting and making a field read-only when using the release-profile. Should a new issue be created for such a feature?

**Comment by martin-t** [comment]
Can you tell me a bit about what you want the attribute for?

I think long-term i'll add C# style property getters and setters. What you want could probably be supported by those but i wonder why you even want a *configuration* variable that can't be configured.

**Comment by martin-t** [comment]
Only took over a year but the latest published version now supports skipping fields.

I don't think more attributes like `readonly` are worth the complexity. I'd rather add a way to hook into the way consoles execute commands so gamedevs can do whatever they want there and for example only allow players to set cvars with certain prefixes.
